name: rnagps
channels:
  - defaults
  - anaconda
  - pytorch
  - conda-forge
  - bioconda
dependencies:
  - python=3.7.3
  - numpy=1.16.3
  - pandas=0.24.2
  - scipy=1.2.1
  - scikit-learn=0.21.3
  - matplotlib=3.0.3
  - seaborn=0.9.0
  - tqdm
  - pytorch
  - pyfaidx
  - intervaltree
